---
output: github_document
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# boundid

The goal of boundid is to ...

## Installation

You can install the development version of boundid like so:

``` r
devtools::install_github("fresej/boundid")
```

## Example

This is a basic example using simulated data to demonstrate how to use the boundid package to estimate boundary bias and adjust for it with the weighting and the trimming approach in a classic 2x2 DiD setup:

```{r example}
library(boundid)
library(tidyverse)
library(fixest)

# Data simulation
set.seed(123)
n <- 500

time_1 <- data.frame(
  ID = 1:n,
  X = rnorm(n, mean = 10, sd = 3)
)

time_2 <- data.frame(
  ID = 1:n,
  X = rnorm(n, mean = 7, sd = 3)
)

simulated_data_1 <- rbind(
  cbind(time_1, time = 0),  
  cbind(time_2, time = 1)  
)

simulated_data_1$treated <- 0

time_3 <- data.frame(
  ID = (n+1):(2*n),
  X = rnorm(n, mean = 6, sd = 3)
)

time_4 <- data.frame(
  ID = (n+1):(2*n),
  X = rnorm(n, mean = 6, sd = 3)
)

simulated_data_2 <- rbind(
  cbind(time_3, time = 0), 
  cbind(time_4, time = 1)  
)

simulated_data_2$treated <- 1

simulated_data <- rbind(simulated_data_1, simulated_data_2)

simulated_data <- simulated_data %>% 
  arrange(ID, time)

means <- simulated_data %>%
  group_by(time, treated) %>%
  summarise(mean_X = mean(X, na.rm = TRUE))

ggplot(means, aes(x = factor(time), y = mean_X, color = factor(treated))) +
  geom_point(size = 3) +
  labs(title = "Mean of X for Time Periods and Treatment Groups",
       x = "Time Period", y = "Mean of X", color = "Treatment Group") +
  scale_color_manual(values = c("blue", "red")) +
  theme_minimal()

# run test
boundid_test(simulated_data, "X", 0, floor = T, simulated_data$treated, simulated_data$time, more_info = T, ID = "ID")

# create weights
test_weights <- boundid_adjust(simulated_data, "X", 0, floor = T,treatment = simulated_data$treated, time = simulated_data$time,
               ID = simulated_data$ID, ATT = T, cut = F, panel = F,orig_ID = simulated_data$ID)

# cut observations
test_cuts <- boundid_adjust(simulated_data, "X", 0, floor = T,treatment = simulated_data$treated, time = simulated_data$time,
                       ID = simulated_data$ID, ATT = T, cut = T, panel = F,orig_ID = simulated_data$ID)


table(test_weights)

table(test_cuts)


```



